# Code style checking for RSpec Rails files. A plugin for the RuboCop code style
# enforcing & linting tool.
#
# @see https://rubygems.org/gems/rubocop-rspec_rails
# @see https://docs.rubocop.org/rubocop-rspec_rails
# @see https://github.com/rubocop/rubocop-rspec_rails

require: rubocop-rspec_rails
