# A collection of RuboCop cops to check for performance optimizations in Ruby
# code.
#
# @see https://rubygems.org/gems/rubocop-performance
# @see https://docs.rubocop.org/rubocop-performance
# @see https://github.com/rubocop/rubocop-performance

require: rubocop-performance

Performance/ChainArrayAllocation:
  Enabled: true

Performance/IoReadlines:
  Enabled: true

Performance/OpenStruct:
  Enabled: true

Performance/SelectMap:
  Enabled: true
