require: rubocop-performance

Performance/ChainArrayAllocation:
  Enabled: true

Performance/IoReadlines:
  Enabled: true

Performance/OpenStruct:
  Enabled: true

Performance/SelectMap:
  Enabled: true
