# Metrics cops deal with properties of the source code that can be measured,
# such as class length, method length, etc.
#
# @see https://docs.rubocop.org/rubocop/cops_metrics.html

Metrics/BlockLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

Metrics/ClassLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

Metrics/MethodLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

Metrics/ModuleLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

Metrics/ParameterLists:
  CountKeywordArgs: false
